/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1;

/**
 *
 * @author xp
 */
public class diseño extends javax.swing.JFrame {

    /**
     * Creates new form diseño
     */
    public diseño() {
        initComponents();
        setSize(730,350);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        NombreArchivo = new javax.swing.JTextField();
        Escribir = new javax.swing.JButton();
        Leer = new javax.swing.JButton();
        Texto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("     NOMBRE DEL ARCHIVO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 250, -1));

        NombreArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(NombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 270, 40));

        Escribir.setBackground(new java.awt.Color(255, 255, 255));
        Escribir.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Escribir.setText("ESCRIBIR");
        Escribir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EscribirMouseClicked(evt);
            }
        });
        getContentPane().add(Escribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 130, 40));

        Leer.setBackground(new java.awt.Color(255, 255, 255));
        Leer.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Leer.setText("LEER");
        Leer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LeerMouseClicked(evt);
            }
        });
        getContentPane().add(Leer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 130, 40));
        getContentPane().add(Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 460, 250));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreArchivoActionPerformed

    private void LeerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LeerMouseClicked

    private void EscribirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscribirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EscribirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new diseño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Escribir;
    private javax.swing.JButton Leer;
    private javax.swing.JTextField NombreArchivo;
    private javax.swing.JTextField Texto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
